name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: lambda
        run: npm ci

      - name: Typecheck
        working-directory: lambda
        run: npm run typecheck

      - name: Run tests
        working-directory: lambda
        run: npm test
